import { styleTags, tags as t } from "@lezer/highlight";

export const jarvilHighlighting = styleTags({
  "for while if elif else return break continue": t.controlKeyword,
  "in not and or": t.operatorKeyword,
  "def type lambda let interface implements struct": t.definitionKeyword,
  import: t.moduleKeyword,
  print: t.keyword,
  None: t.null,
  VariableName: t.variableName,
  "CallExpression/VariableName": t.function(t.variableName),
  "FunctionDefinition/VariableName": t.function(t.definition(t.variableName)),
  "StructTypeDefinition/VariableName": t.definition(t.typeName),
  "LambdaTypeDefinitionStatement/VariableName": t.definition(t.typeName),
  PropertyName: t.propertyName,
  "CallExpression/MemberExpression/PropertyName": t.function(t.propertyName),
  LineComment: t.lineComment,
  BlockComment: t.blockComment,
  Boolean: t.bool,
  Number: t.number,
  String: t.string,
  // Integer: t.integer,
  // Float: t.float,
  self: t.self,
  FormatString: t.special(t.string),
  "ArithOp!": t.arithmeticOperator,
  CompareOp: t.compareOperator,
  AssignOp: t.definitionOperator,
  FieldIdentifier: t.propertyName,
  TypeIdentifier: t.typeName,
  "->": t.punctuation,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
  ".": t.derefOperator,
  ", ; ::": t.separator,
});
